[tool.poetry]
name = "sar_ms_py"
version = "v2.12.0"
description = "This repository corresponds to the a small python microservice that is going to be used used in the sar system."
authors = ["joseesco24 <josed.escobar@outlook.com>"]
readme = "readme.md"
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.0"
loguru = "^0.7.0"
pydantic = "^2.0.2"
uvicorn = "^0.24.0"
pydantic-settings = "^2.0.3"
pymysql = "^1.1.0"
cryptography = "^42.0.5"
sqlmodel = "^0.0.16"
httpx = "^0.27.0"
cachetools = "^5.3.3"
stamina = "^24.2.0"
asyncache = "^0.3.1"
pytz = "^2024.1"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
mypy = "^1.0.0"
watchfiles = "^0.21.0"
flake8 = "^7.0.0"
pytest = "^8.0.2"
pytest-asyncio = "^0.23.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
