[tool.poetry]
name = "sar_ms_py"
version = "v1.0.0"
description = "This repository corresponds to the a small python microservice that is gint to be used used in the sar system."
authors = ["joseesco24 <josed.escobar@outlook.com>"]
readme = "readme.md"
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.0"
psycopg2-binary = "^2.9.5"
SQLAlchemy = "^2.0.1"
loguru = "^0.7.0"
ariadne = "^0.21.0"
redis = "^5.0.0"
psutil = "^5.9.4"
pydantic = { extras = ["dotenv"], version = "^2.0.2" }
uvicorn = "^0.24.0"
pydantic-settings = "^2.0.3"

[tool.poetry.group.dev.dependencies]
black = "^23.1a1"
mypy = "^1.0.0"
watchfiles = "^0.21.0"
wrapt = "^1.14.1"
dill = "^0.3.6"
flake8 = "^6.0.0"
pytest = "^7.2.1"
poetry-plugin-export = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
